#!/bin/sh

# udhcpc script edited by Tim Riker <Tim@Rikers.org>

[ -z "$1" ] && echo "Error: should be called from udhcpc" && exit 1

RESOLV_CONF="/etc/resolv.conf"
ORDER_CONF="/tmp/dnsorder.conf"
ROUTE_CONF="/tmp/routedhcp.conf"
[ -n "$broadcast" ] && BROADCAST="broadcast $broadcast"
[ -n "$subnet" ] && NETMASK="netmask $subnet"

if [ ! -f "$ORDER_CONF" ]; then
    touch "$ORDER_CONF"
fi
if [ ! -f "$ROUTE_CONF" ]; then
    touch "$ROUTE_CONF"
fi

# return 0 if root is mounted on a network filesystem
root_is_nfs() {
	sed -n 's/^[^ ]* \([^ ]*\) \([^ ]*\) .*$/\1 \2/p' /proc/mounts |
	grep -q "^/ \(nfs\|smbfs\|ncp\|coda\)$"
}

have_bin_ip=0
if [ -x /bin/ip ]; then
  have_bin_ip=1
fi

case "$1" in
	deconfig)
		if [ -x /sbin/resolvconf ]; then
			/sbin/resolvconf -d "${interface}.udhcpc"
		fi
		if ! root_is_nfs ; then
                        if [ $have_bin_ip -eq 1 ]; then
                                ip -4 addr flush dev $interface
                                ip link set dev $interface up
                        else
                                /sbin/ifconfig $interface 0.0.0.0
                        fi
		fi
		;;

	renew|bound)
                if [ $have_bin_ip -eq 1 ]; then
                        ip addr add dev $interface local $ip/$mask $BROADCAST
                else
                        /sbin/ifconfig $interface $ip $BROADCAST $NETMASK
                fi
		sed -i "/${interface} /d" ${ROUTE_CONF}
		if [ -n "$router" ] ; then
			if ! root_is_nfs ; then
                                if [ $have_bin_ip -eq 1 ]; then
                                        while ip route del default dev $interface 2>/dev/null ; do
                                                :
                                        done
                                else
                                        while route del default gw 0.0.0.0 dev $interface 2>/dev/null ; do
                                                :
                                        done
                                fi
			fi

			metric=1
			for i in $router ; do
				echo "${interface} ${i}" >> ${ROUTE_CONF}
                                if [ $have_bin_ip -eq 1 ]; then
                                        #ip route add default via $i dev $interface metric $metric
                                        route add default gw $i dev $interface metric $metric 2>/dev/null
                                else
                                        route add default gw $i dev $interface metric $metric 2>/dev/null
                                fi
                                metric=$(($metric + 1))
			done

		fi

		# Update resolver configuration file
		R=""
		[ -n "$domain" ] && R="domain $domain
"
		sed -i "/${interface} /d" ${ORDER_CONF}
		for i in $dns; do
			echo "$0: Adding DNS $i"
			R="${R}nameserver $i
"
			echo "${interface} $i" >> ${ORDER_CONF}
		done
		
		if [ -x /sbin/resolvconf ]; then
			echo -n "$R" | /sbin/resolvconf -a "${interface}.udhcpc"
		else
			echo -n "$R" > "$RESOLV_CONF"
		fi
		
		if [ -x /home/sysuser/util/fixroute ]; then
			/home/sysuser/util/fixroute	
		fi
		;;
esac

exit 0
