#!/bin/sh
### BEGIN INIT INFO
# Provides:          umountfs
# Required-Start:
# Required-Stop:     
# Default-Start:
# Default-Stop:      0 6
# Short-Description: Turn off swap and unmount all local file systems.
# Description:
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

echo "Deactivating swap..."
swapoff -a

# We leave /proc mounted.
echo "Unmounting local filesystems..."
grep -q /mnt/ram /proc/mounts && mount -o remount,ro /mnt/ram
mount -o remount,ro /

umount -f -a -r > /dev/null 2>&1

HN=`cat /proc/board | tr A-Z a-z`
if [ -e /dev/mtd9 ] && [ -b /dev/mtdblock9 ]; then
    if [ "$HN" == "wise2834" ] || [ "$HN" == "adam67c1" ]; then
        # detach data partition
        ubidetach -m 10 &> /dev/null
    else
        # detach recovery partition
        ubidetach -m 10 &> /dev/null
        # detach data partition
        ubidetach -m 11 &> /dev/null
    fi
fi

: exit 0
