#!/bin/sh

/bin/mount -a

/bin/mkdir /dev/pts

/bin/mount -t devpts devpts /dev/pts

echo /sbin/mdev > /proc/sys/kernel/hotplug #//USB自动挂载需要

/sbin/mdev -s         #在/dev下自动创建设备文件节点

HN=`cat /proc/board | tr A-Z a-z`


analysis_disk_config()
{
	disk_config=/root/config
	dos2unix $disk_config
	if [ -f $disk_config ];then
		echo "find disk_config=$disk_config"
		while read line
		do 
			name=`echo $line|awk -F '=' '{print $1}'`
			value=`echo $line|awk -F '=' '{print $2}'`
			case $name in
				"disk_type")
					disk_type=$value
					if [ "$value" != "mmc" ] && [ "$value" != "emmc" ] && [	"$value" != "nand" ];then 
						echo " disk_type=[$value] is not in mmc/emmc/nand type"
					fi
					;;
				"mtd_rfs_num")
					mtd_rfs_num=$value
					;;		
				"mtd_recovery_num")
					mtd_recovery_num=$value
					;;		
				"mtd_data_num")
					mtd_data_num=$value
					;;	
				"mtd_userdata_num")
					mdt_userdata_num=$value
					;;	
				"ubi_root_num")
					ubi_root_num=$value
					;;	
				"ubi_recovery_num")
					ubi_recovery_num=$value
					;;	
				"ubi_data_num")
					ubi_data_num=$value
					;;		
				"ubi_userdata_num")
					ubi_userdata_num=$value
					;;		
				"rootdev")
					rootdev=$value
					;;
				"recoverydev")
					recoverydev=$value
					;;
				"datadev")
					datadev=$value
					;;
			esac
		done < $disk_config
	fi
}

analysis_disk_config

if [ "$disk_type" == "nand" ];then 
    # attach rootfs partition
	if [ -e /dev/mtd${mtd_rfs_num} ];then 
		if [ ! -c /dev/ubi${ubi_root_num} ] && [ "$mtd_rfs_num" != "" ] && [ "$ubi_root_num" != "" ]; then
			ubiattach -p /dev/mtd${mtd_rfs_num} -d ${ubi_root_num} -O 1024
		fi
		if [ ! -c /dev/ubi${ubi_root_num}_0 ]; then
			ubimkvol /dev/ubi${ubi_root_num} -N rootfs -m
		fi
		if [ "$rootdev" != "" ];then 
			mkdir -p /media/$rootdev
        	mount -t ubifs ubi${ubi_root_num}_0 /media/$rootdev 
		else
			echo "rootdev=[$rootdev], mount failed, please check $disk_config"
		fi
	fi

    # attach recovery partition
	if [ -e /dev/mtd${mtd_recovery_num} ] && [ "$mtd_recovery_num" != "" ] && [ "$ubi_recovery_num" != "" ];then 
		if [ ! -c /dev/ubi${ubi_recovery_num} ]; then
			ubiattach -p /dev/mtd${mtd_recovery_num} -d ${ubi_recovery_num} -O 1024
		fi
		if [ ! -c /dev/ubi${ubi_recovery_num}_0 ]; then
			ubimkvol /dev/ubi${ubi_recovery_num} -N rootfs -m
		fi
		if [ "$recoverydev" != "" ];then 
			mkdir -p /media/$recoverydev
        	mount -t ubifs ubi${ubi_recovery_num}_0 /media/$recoverydev 
		else 
			echo "recoverydev=[$recoverydev], mount failed, please check $disk_config"
		fi
	fi

    # attach data partition
	if [ -e /dev/mtd${mtd_data_num} ] && [ "$mtd_data_num" != "" ] && [ "$ubi_data_num" != "" ];then 
		if [ ! -c /dev/ubi${ubi_data_num} ]; then
			ubiattach -p /dev/mtd${mtd_data_num} -d ${ubi_data_num} -O 1024
		fi
		if [ ! -c /dev/ubi${ubi_data_num}_0 ]; then
			ubimkvol /dev/ubi${ubi_data_num} -N rootfs -m
		fi
		if [ "$datadev" != "" ];then 
			mkdir -p /media/$datadev 
        	mount -t ubifs ubi${ubi_data_num}_0 /media/$datadev
		else 
			echo "datadev=[$datadev], mount failed, please check $disk_config"
		fi
	fi
fi

